### ISSUE TITLE
Parsing Help command contents into a seperate TOML file

### ISSUE THREAD

**Issue by ghost** [HiItsDevin/Yiski#10]
Probably would help add commands to the list a lot more easily, than trying to flood [Discord help.py](https://github.com/HiItsDevin/Yiski/blob/main/discordCommands/help.py) and [Revolt help.py](https://github.com/HiItsDevin/Yiski/blob/main/revoltCommands/help.py)

**Comment by ghost** [comment]
I guess here's an example of what could work

```toml
[hello]
name = "Hello"
desc = "Hello Command"
syntax = "{botPrefix}hello"

[httpcat]
name = "HTTP Cat"
desc = "Hello Command"
syntax = "{botPrefix}httpcat [http code]"

[ghr]
name = "GitHub Repos"
desc = "Preview GitHub Repo's Details"
syntax = "{botPrefix}ghr [org/username] [repo name]"

[memoryleak]
name = "Memory Leak"
desc = "Funni Memory Leak video go brrr"
syntax = "{botPrefix}memoryleak"

[gasp]
name = "Gasp"
desc = "Just find out for yourself..."
syntax = "{botPrefix}gasp"

[token]
name = "Token Leak"
desc = "So about that funky config.toml..."
syntax = "{botPrefix}token"

[devtools]
name = "Discord Devtools"
desc = "Discord disabled Dev Tools by default now, here's how to get it back"
syntax = "{botPrefix}devtools"

[headcrab]
name = "Headcrab"
desc = "Do you just... want someone to perish? Throw a headcrab at them!"
syntax = "{botPrefix}headcrab [@username]"
```
